      DROP DATABASE IF EXISTS Aerien;
      
      CREATE DATABASE IF NOT EXISTS Aerien;

      USE Aerien;

      CREATE TABLE IF NOT EXISTS AVION (
      AVION_ID INT NOT NULL AUTO_INCREMENT,
      VERSION VARCHAR(20) NOT NULL,
      CAPACITE INT,
      IMMATR VARCHAR(10),
      LOCALISATION VARCHAR(31),
      PRIMARY KEY(AVION_ID),
      UNIQUE KEY(IMMATR)
      ) ENGINE=INNODB;

      CREATE TABLE IF NOT EXISTS PILOTE (
      PILOTE_ID INT NOT NULL AUTO_INCREMENT,
      NOMPIL VARCHAR(31) NOT NULL,
      ADRESSE VARCHAR(31),
      SALAIRE INT,
      PRIME INT,
      PRIMARY KEY(PILOTE_ID)
      ) ENGINE=INNODB;

      CREATE TABLE IF NOT EXISTS VOL (
      VOL_ID INT NOT NULL AUTO_INCREMENT,
      AVION_ID INT NOT NULL,
      PILOTE_ID INT NOT NULL,
      VILLE_DEP VARCHAR(31),
      VILLE_ARR VARCHAR(31),
      HEURE_DEP DATETIME,
      HEURE_ARR DATETIME,
      PRIMARY KEY(VOL_ID),
      FOREIGN KEY (AVION_ID) REFERENCES AVION(AVION_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
      FOREIGN KEY (PILOTE_ID) REFERENCES PILOTE(PILOTE_ID) ON UPDATE CASCADE ON DELETE RESTRICT
      ) ENGINE=INNODB;

INSERT INTO PILOTE (NOMPIL,ADRESSE,SALAIRE,PRIME) VALUES ('Bob','Kingstown',3001,1200);
INSERT INTO PILOTE (NOMPIL,ADRESSE,SALAIRE,PRIME) VALUES ('Jimi','London',2300,2100);
INSERT INTO PILOTE (NOMPIL,ADRESSE,SALAIRE,PRIME) VALUES ('George','Marseille',4500,501);
INSERT INTO PILOTE (NOMPIL,ADRESSE,SALAIRE,PRIME) VALUES ('John','Marseille',2899,100);
INSERT INTO PILOTE (NOMPIL,ADRESSE,SALAIRE,PRIME) VALUES ('Paul','Liverpool',3200,1659);
INSERT INTO PILOTE (NOMPIL,ADRESSE,SALAIRE,PRIME) VALUES ('Ringo','Liverpool',5000,320);
INSERT INTO PILOTE (NOMPIL,SALAIRE,PRIME) VALUES ('Meki',5000,1232);
INSERT INTO PILOTE (NOMPIL,ADRESSE,SALAIRE) VALUES ('Toki','Bordeaux',2600);
INSERT INTO PILOTE (NOMPIL,ADRESSE,SALAIRE,PRIME) VALUES ('Bran','Paris',6000,220);
INSERT INTO PILOTE (NOMPIL,ADRESSE,SALAIRE,PRIME) VALUES ('Bobo','Paris',2000,200);
INSERT INTO PILOTE (NOMPIL,ADRESSE,SALAIRE,PRIME) VALUES ('Cec','Marseille',7000,1220);

INSERT INTO AVION (VERSION,CAPACITE,IMMATR,LOCALISATION) VALUES ('A320',150,'F-HPJB','Paris');
INSERT INTO AVION (VERSION,CAPACITE,IMMATR,LOCALISATION) VALUES ('A321',190,'D-AIMB','Los Angeles');
INSERT INTO AVION (VERSION,CAPACITE,IMMATR,LOCALISATION) VALUES ('A319',130,'A6-EDM','Chicago');
INSERT INTO AVION (VERSION,CAPACITE,IMMATR,LOCALISATION) VALUES ('A318',100,'F-HPJC','Paris');
INSERT INTO AVION (VERSION,CAPACITE,IMMATR,LOCALISATION) VALUES ('A330',335,'F-HPJD','Marseille');
INSERT INTO AVION (VERSION,CAPACITE,IMMATR,LOCALISATION) VALUES ('A340',313,'D-AIMC','Marseille');
INSERT INTO AVION (VERSION,CAPACITE,IMMATR,LOCALISATION) VALUES ('A350 XWB',395,'E-BJND','Paris');
INSERT INTO AVION (VERSION,CAPACITE,IMMATR,LOCALISATION) VALUES ('A380',555,'A6-EDN','Paris');

INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP,HEURE_ARR) VALUES (1,1,'Paris','Los Angeles', '2011-2-13 10:05:00', '2011-2-13 19:35:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP,HEURE_ARR) VALUES (2,2,'Paris','Liverpool', '2011-2-13 19:05:00', '2011-2-13 18:35:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP,HEURE_ARR) VALUES (2,3,'Carnoux','Luminy', '2011-2-13 18:05:00', '2011-2-13 19:35:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP,HEURE_ARR) VALUES (3,4,'Paris','Mazargues', '2011-2-13 17:05:00', '2011-2-13 19:35:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP,HEURE_ARR) VALUES (3,5,'Cassis','Roquefort-la-Bédoule', '2011-2-13 16:05:00', '2011-2-13 18:05:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP,HEURE_ARR) VALUES (3,1,'Vaufrèges','Aubagne', '2011-2-14 15:05:00', '2011-2-14 15:35:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP,HEURE_ARR) VALUES (4,2,'Aubagne','Saint-Loup', '2011-2-15 15:05:00', '2011-2-15 17:05:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP,HEURE_ARR) VALUES (4,3,'Paris','Saint-Loup', '2011-2-16 15:05:00', '2011-2-16 16:05:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP) VALUES (4,4,'Aubagne','Los Angeles', '2011-2-17 15:05:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP) VALUES (4,1,'Aubagne','Liverpool', '2011-2-18 15:05:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP) VALUES (5,2,'Liverpool','Saint-Loup', '2011-2-19 15:05:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP) VALUES (5,3,'Aubagne','Saint-Loup', '2011-2-20 15:05:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP) VALUES (5,1,'Liverpool','Saint-Loup', '2011-2-21 15:05:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP) VALUES (5,2,'Aubagne','Saint-Loup', '2011-2-22 15:05:00');
INSERT INTO VOL (AVION_ID,PILOTE_ID,VILLE_DEP,VILLE_ARR,HEURE_DEP) VALUES (5,1,'Saint-Loup','Carnoux', '2011-2-23 15:05:00');